tunnel: b99c8f55-ec1a-4a4f-85f1-a076ff23c919
credentials-file: /home/container/.cloudflared/b99c8f55-ec1a-4a4f-85f1-a076ff23c919.json
origincert: /home/container/.cloudflared/cert.pem

ingress:
  - hostname: verify.marvellousbot.win
    service: http://localhost:5012
  - service: http_status:404